// Tab 1
export const STARGATE_HOME = 'STARGATE_HOME';
export const STARGATE_DETAILS = 'STARGATE_DETAILS';
// Tab 2
export const BATMAN_HOME = 'BATMAN_HOME';
export const BATMAN_DETAILS = 'BATMAN_DETAILS';
// Tab 3
export const SPIDERMAN_HOME = 'SPIDERMAN_HOME';
export const SPIDERMAN_DETAILS = 'SPIDERMAN_DETAILS';
